[package]
name = "mycli"
version = "0.1.0"
edition = "2024"

[dependencies]
rand = "0.9.2"
regex = "1.12.2"
reqwest = { version = "0.12", features = ["blocking", "json"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
structopt = "0.3"
